Controllers/ScheduleController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using IFNMUSiteCore.Models;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Xml.Serialization;
using System.IO;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using System;
using System.Web;
using Microsoft.AspNetCore.Authorization;
using Microsoft.Extensions.Hosting;
using Microsoft.AspNetCore.Identity;
using System.Text.RegularExpressions;
using System.Text.Json;

namespace IFNMUSiteCore.Controllers
{
    [Authorize(Roles = "moderator")]
    public class ScheduleController : Controller
    {
        readonly private LessonContext db; // контекст БД
        readonly private IWebHostEnvironment _appEnvironment;
        readonly private UserManager<User> _users;

        public ScheduleController(LessonContext context, IWebHostEnvironment appEnvironment, UserManager<User> userManager) // конструктор
        {
            db = context;
            _appEnvironment = appEnvironment;
            _users = userManager;
        }
        public ActionResult Index()
        {
            return View();
        }
        // Сторінка "Додати день до розкладу"
        [HttpGet]
        public ActionResult AddWeek()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> AddWeek(Week w)
        {
            try
            {
                w.Faculty = FacultyDetermine(w.Group);
                await db.Weeks.AddAsync(w);
                await db.ScheduleDays.AddRangeAsync(w.ScheduleDays);
                await db.SaveChangesAsync();
                List<Lesson>[] les = new List<Lesson>[5];
                for (byte a = 0; a < 5; a++)
                {
                    les[a] = new List<Lesson>();
                    for (int i = 0; i < HttpContext.Request.Form["ScheduleDays[" + a + "].Lessons[].LessonNumber"].Count; i++)
                    {
                        les[a].Add(new Lesson()
                        {
                            Name = HttpContext.Request.Form["ScheduleDays[" + a + "].Lessons[].Name"][i],
                            LessonNumber = Convert.ToInt32(HttpContext.Request.Form["ScheduleDays[" + a + "].Lessons[].LessonNumber"][i]),
                            ScheduleDayId = w.ScheduleDays[a].Id
                        });

                    }
                    await db.Lessons.AddRangeAsync(les[a]);
                }
                await db.SaveChangesAsync();
                return View();
            }
            catch (Exception e)
            {
                return BadRequest("Помилка запиту (" + e.Message + ")");
            }
        }
        // Додати урок
        public IActionResult AddLesson(byte dayNumber, byte index)
        {
            return PartialView(dayNumber);
        }
        [HttpGet]
        public IActionResult EditWeek(int course, string group)
        {
            return View(db.Weeks.Where(w => w.Course == course && w.Group == group).Include(s => s.ScheduleDays).ThenInclude(sch => sch.Lessons).ToList());
        }
        [HttpGet]
        public IActionResult EditDay(int id)
        {
            return View(db.ScheduleDays.Include(a => a.Lessons).Single(i => i.Id == id));
        }
        [HttpGet]
        public async Task<IActionResult> EditLesson(int id)
        {
            ViewBag.Chairs = await db.Chairs.ToListAsync();
            Lesson lesson = await db.Lessons.Include(c => c.Chair).SingleAsync(l => l.Id == id);
            if (lesson.Chair != null)
            {
                ViewBag.Chairs.Remove(lesson.Chair);
            }
            Chair l = await db.Chairs.SingleOrDefaultAsync(a => a.Name.Contains("Тематичні"));
            Chair al = await db.Chairs.SingleOrDefaultAsync(a => a.Name.Contains("Методичні"));
            ViewBag.Chairs.Remove(al);
            ViewBag.Chairs.Remove(l);
            return View(lesson);
        }
        [HttpPost]
        public IActionResult EditLesson(Lesson lesson)
        {
            if (lesson != null)
            {
                if (HttpContext.Request.Form["ChairId"] != "null")
                {
                    lesson.ChairId = Convert.ToInt32(HttpContext.Request.Form["ChairId"]);
                }
                if (HttpContext.Request.Form["ThematicPlanId"] != "null")
                {
                    lesson.ThematicPlanId = Convert.ToInt32(HttpContext.Request.Form["ThematicPlanId"]);
                }
                if (HttpContext.Request.Form["MethodicalRecomendationId"] != "null")
                {
                    lesson.MethodicalRecomendationId = Convert.ToInt32(HttpContext.Request.Form["MethodicalRecomendationId"]);
                }

                db.Update(lesson);
                db.SaveChanges();
            }
            return RedirectToAction("EditDay", new { id = lesson.ScheduleDayId });
        }

        [HttpGet]
        public IActionResult DeleteLesson(int id)
        {
            return View(db.Lessons.Find(id));
        }
        [HttpPost]
        public IActionResult DeleteLesson(Lesson lesson)
        {
            int Id = lesson.Id;
            Lesson les = db.Lessons.FirstOrDefault(l => l.Id == lesson.Id);
            db.Remove(les);
            db.SaveChanges();
            return RedirectToAction("EditDay", new { id = Id });
        }
        [HttpGet]
        public IActionResult AddLessonOne(int id)
        {
            return View(id);
        }
        [HttpPost]
        public IActionResult AddLessonOne(Lesson lesson)
        {
            db.Add(lesson);
            db.SaveChanges();
            return RedirectToAction("EditDay", new { id = lesson.ScheduleDayId });
        }

        [HttpGet]
        public IActionResult EditMRTP(int? count = null)
        {
            ViewBag.CountUpdate = count;
            return View(db.Chairs.ToList());
        }
        [HttpPost]
        public async Task<IActionResult> EditMRTP(string nameLesson, int numberCourse, Faculty faculty, int? MethodicalRecomendationId, int? ThematicPlanId, string group, int regexIndex, int? idChair)
        {
            // @"патоморфологія Л\d*" - лекція
            // @"патоморфологія$" - "Патоморфологія"
            // @"патоморфологія \(\w*" - (підгрупа, клінічка)
            List<Week> week;
            if (group == null || group.Trim() == "" || group == "")
            {
                week = await db.Weeks.Where(p => p.Course == numberCourse && p.Faculty == faculty).Include(s => s.ScheduleDays).ThenInclude(les => les.Lessons).ToListAsync();
            }
            else
            {
                week = await db.Weeks.Where(p => p.Course == numberCourse && p.Group.ToLower() == group.ToLower()).Include(s => s.ScheduleDays).ThenInclude(les => les.Lessons).ToListAsync();
            }
            Regex regex = null;
            Regex regex2 = null;
            if (regexIndex == 1)
            {
                if (nameLesson.Contains("підгрупа") || nameLesson.Contains("клінічка") || nameLesson.Contains("(") || nameLesson.Contains(")"))
                {
                    nameLesson = nameLesson.Replace("підгрупа ", @"підгрупа\s").Replace("клінічка", @"клінічка\s").Replace("(", @"\(").Replace(")", @"\)");
                    regex = new Regex(nameLesson, RegexOptions.IgnoreCase | RegexOptions.Compiled);
                }
                else
                {
                    regex = new Regex(@$"{nameLesson}$", RegexOptions.IgnoreCase | RegexOptions.Compiled);
                    regex2 = new Regex(@$"{nameLesson}\(\w*", RegexOptions.IgnoreCase | RegexOptions.Compiled);
                }
            }
            else regex = new Regex(@$"{nameLesson} Л\d*", RegexOptions.IgnoreCase | RegexOptions.Compiled);
            MatchCollection matches;
            List<Lesson> lessons = new List<Lesson>();
            foreach (Week w in week)
            {
                foreach (ScheduleDay scheduleDay in w.ScheduleDays)
                {
                    foreach (Lesson lesson in scheduleDay.Lessons)
                    {
                        matches = regex.Matches(lesson.Name);
                        if (matches.Count > 0) lessons.Add(lesson);
                        matches = regex2.Matches(lesson.Name);
                        if (matches.Count > 0) lessons.Add(lesson);
                    }
                }
            }
            for (int i = 0; i < lessons.Count; i++)
            {
                lessons[i].MethodicalRecomendationId = MethodicalRecomendationId;
                lessons[i].ThematicPlanId = ThematicPlanId;
                lessons[i].ChairId = idChair;
            }
            db.Lessons.UpdateRange(lessons);
            await db.SaveChangesAsync();
            return RedirectToAction("EditMRTP", new { count = lessons.Count() });
        }

        [HttpGet]
        public IActionResult AddSchedule()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> AddSchedule(string[][] item, string[] potikName, string[] potikGroups, byte course)
        {
            bool subGroup = true;
            List<Week> weeks = new List<Week>();

            for (byte i = 0; i < item.Length; i++)
            {
                for (byte j = 1; j < item[i].Length; j++)
                {
                    if (item[i][j] == null) continue;
                    if (item[i][j].Contains("*"))
                    {
                        subGroup = false;
                        break;
                    }
                }

                for (byte j = 1; j < item[i].Length; j++)
                {
                    if (item[i][j] == null) continue;
                    string[] splitItems = item[i][j].Split(" ");

                    byte lessonNumber = 0;
                    byte dayNumber = 0;
                    byte weekNumber = 0;

Views/Schedule/AddLesson.cshtml
@model byte
@{Layout = null;
    }
<div style="border-bottom: 2px solid green; border-top: 2px solid green; padding: 5% 0;">
    <div class="form-group">
        <label for="ScheduleDays[@Model].Lessons[].LessonNumber">Номер заняття</label>
        <input class="form-control" name="ScheduleDays[@Model].Lessons[].LessonNumber" id="ScheduleDays[@Model].Lessons[].LessonNumber" type="number" value="">
    </div>

    <div class="form-group">
        <label for="ScheduleDays[@Model].Lessons[].Name">Назва заняття</label>
        <input class="form-control" name="ScheduleDays[@Model].Lessons[].Name" id="ScheduleDays[@Model].Lessons[].Name" type="text" value="">
    </div>
</div>
<br />

Views/Schedule/AddLessonOne.cshtml
@model int
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>AddLessonOne</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>
    <div class="container">
        <form method="post" asp-action="AddLessonOne">
                <input type="hidden" name="ScheduleDayId" value="@Model"/>
            <div class="form-group">
                <label for="">Номер заняття</label>
                <input class="form-control" name="LessonNumber" id="LessonNumber" type="number" value="">
            </div>
            <div class="form-group">
                <label for="">Назва заняття</label>
                <input class="form-control" name="Name" id="Name" type="text" value="">
            </div>
            <input class="btn btn-warning" type="submit" value="Додати"/>
        </form>
    </div>
</body>
</html>

Views/Schedule/AddRow.cshtml
@model int
@{
    Layout = null;
}
<tr>
    @for (byte i = 0; i < 41; i++)
    {
        <td>
            <input name="item[@Model][@i]" type="text" style="width:100%;" />
        </td>
    }
</tr>

Views/Schedule/AddSchedule.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>AddSchedule</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <style>
        .table td {
            padding: 0;
        }

        tbody td {
            width: 100px;
        }

            tbody td:nth-child(1) {
                width: 250px;
            }
    </style>
</head>
<body>
    <div class="table-responsive" style="overflow-x: auto; width:3000px;">
        <form method="post" asp-action="AddSchedule">
            <table class="table-bordered" style="text-align: center;">
                <thead class="thead-inverse" style="background-color: lightgoldenrodyellow;">
                    <tr>
                        <td rowspan="3">Назва дисципліни</td>
                        <td colspan="25">Перший тиждень</td>
                        <td colspan="25">Другий тиждень</td>
                    </tr>
                    <tr>
                        <td colspan="4">Понеділок</td>
                        <td colspan="4">Вівторок</td>
                        <td colspan="4">Середа</td>
                        <td colspan="4">Четвер</td>
                        <td colspan="4">П'ятниця</td>
                        <td colspan="4">Понеділок</td>
                        <td colspan="4">Вівторок</td>
                        <td colspan="4">Середа</td>
                        <td colspan="4">Четвер</td>
                        <td colspan="4">П'ятниця</td>
                    </tr>
                    <tr>
                        <td>1</td>
                        <td>2</td>
                        <td>3</td>
                        <td>4</td>

                        <td>1</td>
                        <td>2</td>
                        <td>3</td>
                        <td>4</td>

                        <td>1</td>
                        <td>2</td>
                        <td>3</td>
                        <td>4</td>

                        <td>1</td>
                        <td>2</td>
                        <td>3</td>
                        <td>4</td>

                        <td>1</td>
                        <td>2</td>
                        <td>3</td>
                        <td>4</td>

                        <td>1</td>
                        <td>2</td>
                        <td>3</td>
                        <td>4</td>

                        <td>1</td>
                        <td>2</td>
                        <td>3</td>
                        <td>4</td>

                        <td>1</td>
                        <td>2</td>
                        <td>3</td>
                        <td>4</td>

                        <td>1</td>
                        <td>2</td>
                        <td>3</td>
                        <td>4</td>

                        <td>1</td>
                        <td>2</td>
                        <td>3</td>
                        <td>4</td>

                    </tr>
                </thead>
                <tbody id="tbodyId">
                    <tr>
                        @for (byte i = 0; i < 41; i++)
                        {
                            <td>
                                <input name="item[0][@i]" type="text" style="width:100%;" />
                            </td>
                        }
                    </tr>
                </tbody>
                <tfoot>
                    <tr>
                        <td colspan="5">
                            <a id="idA" class="btn btn-warning" data-ajax="true" data-ajax-mode="after" data-ajax-update="#tbodyId" href="/Schedule/AddRow?index=0">Додати новий рядок</a>
                        </td>
                    </tr>
                </tfoot>
            </table>
            <hr />
            <div class="form-group">
            <div id="potikContainer"></div>
            <div id="addPotik" class="btn btn-danger">Додати потік</div>
            </div>
            <hr />
            <div class="form-group">
                <label for="course">Курс</label>
                <div>
                    <input type="number" class="form-control" id="course" name="course" placeholder="Курс" />
                </div>
            </div>
            <input type="submit" class="btn btn-success" value="Додати розклад" />
        </form>
    </div>
    <script src="~/Scripts/jquery-3.3.1.min.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
    <script>
        let i = 0;

        var link = document.getElementById("idA");

        function A() {
            i++;
            link.href = "/Schedule/AddRow?index=" + i;
        }
        link.addEventListener('click', function () { A(); }, false);

         let htmlPotik = ' <div class="form-group"><label for="potikName">Потік (літера):</label><div><input type="text" class="form-control" id="potikName" name="potikName" placeholder="Потік" /></div><label for="potikGroups">Групи потоку:</label> <div> <input type="text" class="form-control" id="potikGroups" name="potikGroups" placeholder="Групи потоку (через пробіл)" /></div> </div>';
        $("#addPotik").on("click", function () { $("#potikContainer").append(htmlPotik); });
    </script>
</body>
</html >

Views/Schedule/AddWeek.cshtml
@using IFNMUSiteCore.Models
@model Week

@{
    Layout = null; }

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>AddDay</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>
    <div class="container">
        <form asp-action="AddWeek" asp-controller="Schedule" method="post">
            <div class="form-group">
                <label for="From">Від</label>
                <div class="alert alert-primary" role="alert">
                    Залиште поле пустим якщо у вас тільки <strong>два</strong> тижні.
                </div>
                <input class="form-control" type="date" asp-for="From" />
            </div>
            <div class="form-group">
                <label for="To">До</label>
                <div class="alert alert-primary" role="alert">
                    Залиште поле пустим якщо у вас тільки <strong>два</strong> тижні.
                </div>
                <input class="form-control" type="date" asp-for="To" />
            </div>
            <div class="form-group">
                <label for="NumberWeek">Номер тижня</label>
                <div class="alert alert-primary" role="alert">
                    Залиште поле за замовчуванням <strong>1</strong> якщо ви вказали "Від/До"
                </div>
                <input class="text-box single-line form-control" asp-for="NumberWeek" type="number" value="1">
            </div>
            <div class="form-group">
                <label for="Course">Курс</label>
                <input class="text-box single-line form-control" data-val="true" data-val-required="The Courses field is required." asp-for="Course" type="number" max="6" min="1" value="">
            </div>
            <div class="form-group">
                <label for="Group">Група</label>
                <input class="text-box single-line form-control" asp-for="Group" type="text" value="">
            </div>
            <div class="form-group">
                <h3>Понеділок</h3>
                <input type="hidden" name="ScheduleDays[0].DayNumber" value="1" />
                <div class="form-group">
                    <div id="lessonBlock1" style="border: 1px solid black;padding: 5%;">
                    </div>
                    <a class="aj" data-ajax="true" data-ajax-mode="after" data-ajax-update="#lessonBlock1" href="/Schedule/AddLesson?dayNumber=0&index=0">Додати заняття</a>
                </div>
            </div>
            <div class="form-group">
                <h3>Вівторок</h3>
                <input type="hidden" name="ScheduleDays[1].DayNumber" value="2" />
                <div class="form-group">
                    <div id="lessonBlock2" style="border: 1px solid black;padding: 5%;">
                    </div>
                    <a class="aj" data-ajax="true" data-ajax-mode="after" data-ajax-update="#lessonBlock2" href="/Schedule/AddLesson?dayNumber=1&index=0">Додати заняття</a>
                </div>
            </div>
            <div class="form-group">
                <h3>Середа</h3>
                <input type="hidden" name="ScheduleDays[2].DayNumber" value="3" />
                <div class="form-group">
                    <div id="lessonBlock3" style="border: 1px solid black;padding: 5%;">
                    </div>
                    <a class="aj" data-ajax="true" data-ajax-mode="after" data-ajax-update="#lessonBlock3" href="/Schedule/AddLesson?dayNumber=2&index=0">Додати заняття</a>
                </div>
            </div>
            <div class="form-group">
                <h3>Четвер</h3>
                <input type="hidden" name="ScheduleDays[3].DayNumber" value="4" />
                <div class="form-group">
                    <div id="lessonBlock4" style="border: 1px solid black;padding: 5%;">
                    </div>
                    <a class="aj" data-ajax="true" data-ajax-mode="after" data-ajax-update="#lessonBlock4" href="/Schedule/AddLesson?dayNumber=3&index=0">Додати заняття</a>
                </div>
            </div>
            <div class="form-group">
                <h3>П'ятниця</h3>
                <input type="hidden" name="ScheduleDays[4].DayNumber" value="5"/>
                <div class="form-group">
                    <div id="lessonBlock5" style="border: 1px solid black;padding: 5%;">
                    </div>
                    <a class="aj" data-ajax="true" data-ajax-mode="after" data-ajax-update="#lessonBlock5" href="/Schedule/AddLesson?dayNumber=4&index=0">Додати заняття</a>
                </div>
            </div>
            <input type="submit" class="btn btn-primary" value="Додати">
        </form>
    </div>
    <script>
        let i = 0;

        var link = document.getElementsByClassName("aj");
        function A() {
            i++;
            link[0].href = "/Schedule/AddLesson?dayNumber=0&index=" + i;
            link[1].href = "/Schedule/AddLesson?dayNumber=1&index=" + i;
            link[2].href = "/Schedule/AddLesson?dayNumber=2&index=" + i;
            link[3].href = "/Schedule/AddLesson?dayNumber=3&index=" + i;
            link[4].href = "/Schedule/AddLesson?dayNumber=4&index=" + i;
        }
        link[0].addEventListener('click', function () { A(); }, false);
        link[1].addEventListener('click', function () { A(); }, false);
        link[2].addEventListener('click', function () { A(); }, false);
        link[3].addEventListener('click', function () { A(); }, false);
        link[4].addEventListener('click', function () { A(); }, false);
    </script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

Views/Schedule/EditDay.cshtml
@model ScheduleDay
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>EditDay</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>
    <div class="container">
        <table class="table">
     
            @foreach (var item in Model.Lessons.OrderBy(les => les.LessonNumber))
            {
                <tr>
                    <td>@item.Name</td>
                    <td>@item.LessonNumber</td>
                    <td>
                        <a class="btn btn-primary" asp-action="EditLesson" asp-controller="Schedule" asp-route-id="@item.Id">Змінити</a> |
                        <a class="btn btn-danger" asp-action="DeleteLesson" asp-controller="Schedule" asp-route-id="@item.Id">Видалити</a>
                    </td>
                </tr>
            }
        </table>
        <a href="/Schedule/AddLessonOne/@Model.Id">Додати урок</a>
    </div>
</body>
</html>

Views/Schedule/EditMRTP.cshtml
@model List<IFNMUSiteCore.Models.Chair>
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>EditMRTP</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>
    <div class="container">
        @if (ViewBag.CountUpdate != null)
        {
            <div class="alert alert-primary" role="alert">
                Ви змінили дані для <strong>@ViewBag.CountUpdate</strong> занять
            </div>
        }
    <form method="post" asp-controller="Schedule" asp-action="EditMRTP">
        <div class="form-group">
            <label for="nameLesson">Введіть назву дисципліни, для якої будуть змінені дані</label>
            <input class="form-control" type="text" name="nameLesson" id="nameLesson" value="" placeholder="Назва предмету" />
        </div>
        <div class="form-group">
            <label for="regexIndex">Виберіть тип заняття</label>
            <select class="form-control" name="regexIndex" id="regexIndex">
                <option value="1">Практичне заняття</option>
                <option value="2">Лекція</option>
            </select>
        </div>
        <div class="form-group">
            <label for="regexIndex">Введіть групу</label>
            <div class="alert alert-warning" role="alert">
                Якщо ви хочете змінити дані цілому курсу, то залиште поле пустим.
            </div>
            <input class="form-control" type="text" name="group" id="group" value="" placeholder="" />
        </div>
        <div class="form-group">
            <label for="numberCourse">Введіть курс, для якого будуть змінені дані</label>
            <input class="form-control" type="number" placeholder="Курс" name="numberCourse" id="numberCourse" />
        </div>
        <div class="form-group">
            <label for="faculty">Виберіть факультет, для якого будуть змінені дані</label>
            <select class="form-control" name="faculty" id="faculty">
                <option value="1">Медичний факультет</option>
                <option value="2">Стоматологічний факультет</option>
                <option value="3">Фармацевтичний факультет</option>
                <option value="4">Педіатричний факультет</option>
                <option value="5">Підготовки іноземних громадян</option>
                <option value="6">Коледж "Фельдшера"</option>
                <option value="7">Коледж "Фармацевти"</option>
                <option value="8">Коледж "Зубні техніки"</option>
                <option value="9">Коледж "Медсестри"</option>
                <option value="10">Ерготерапевти"</option>
            </select>
        </div>
        <div class="form-group">
            <label for="idChair">Виберіть кафедру, з якої будуть завантажені документи</label>
            <select class="form-control selectChair" name="idChair" id="idChair">
                <option value="null">Не вибрано</option>
                @foreach (var a in Model)
                {
                    <option value="@a.Id">@a.Name</option>
                }
            </select>
        </div>
        <div class="form-group">
            <label for="ThematicPlanId">Виберіть тематичний план</label>
            <div class="alert alert-warning" role="alert">
                Дані загрузяться після вибору <strong>кафедри</strong>
            </div>
            <select class="form-control loadDoc" name="ThematicPlanId" id="ThematicPlanId">
                <option value="null">Немає даних</option>
            </select>
        </div>
        <div class="form-group">
            <label for="MethodicalRecomendationId">Виберіть методичну рекомендацію</label>
            <div class="alert alert-warning" role="alert">
                Дані загрузяться після вибору <strong>кафедри</strong>
            </div>
            <select class="form-control loadDoc" name="MethodicalRecomendationId" id="MethodicalRecomendationId">
                <option value="null">Немає даних</option>
            </select>
        </div>
        <div class="form-group">
            <input class="btn btn-success" type="submit" value="Знайти" />
        </div>
    </form>
    </div>

    <script src="~/Scripts/jquery-3.3.1.min.js"></script>
    <script>
        $(document).on('change', '.selectChair', function (e) {
            $.ajax({
                type: "GET",
                url: "/Chair/LoadChairDoc",
                data: { id: e.target.value },
                dataType: "html"
            }).done(function (msg) {
                $(".loadDoc").html(msg);
            });
        });
    </script>
</body>
</html>